name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - .github/workflows/*
      - .assets/*
      - README.md

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      python_ver: 3.8

    steps:
      - uses: actions/checkout@release
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@release
        with:
          python-version: ${{ matrix.python-version }}
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt -t ./lib
          zip -r Flow.Plugin.SudokuKillerCalc.zip . -x '*.git*'
      - name: Publish
        if: success()
        uses: softprops/action-gh-release@release
        with:
          files: 'Flow.Plugin.SudokuKillerCalc.zip'
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
